version: '3.7'
services:
  node:
    container_name: acme_node
    build:
      context: docker/node
    volumes:
      - './:/usr/app'
    working_dir: '/usr/app'
    env_file:
      - .env
    environment:
      DOCKER_HOST: tcp://docker:2375
    command: ['/bin/sh', '-c', 'tail -f /dev/null']
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - docker
  docker:
    container_name: acme_docker
    image: docker:dind
    privileged: true
    environment:
      DOCKER_TLS_CERTDIR:
